### ISSUE TITLE
Transfer request

### ISSUE THREAD

**Issue by jonathanwiesel** [bigluck/alfred2-hash#4]
Hello there,

I really like this workflow, I tried to make a contribution some time ago but it seems the project is abandoned. If you agree I would like to take care of the project, either as a contributor or even as main owner of the project.

This way the community can still contribute to the project and reach more people with it.

**Comment by bigluck** [comment]
You're welcome :+1:

**Comment by jonathanwiesel** [comment]
Cool. Thank you :+1:
